### ISSUE TITLE
First click of burger menu not working

### ISSUE THREAD

**Issue by Android63** [NHSLeadership/nightingale#108]
On a mobile screen (or small browser window), clicking the burger menu causes its icon to change to an "X" but the mobile menu doesn't get displayed until the button is clicked again - at which point the icon on the button is out of synch with the state of the menu.
![screen shot 2017-07-18 at 15 23 44](https://user-images.githubusercontent.com/1991226/28322258-8c3331a6-6bcd-11e7-97d2-944fa9b3e408.png)
![screen shot 2017-07-18 at 15 25 58](https://user-images.githubusercontent.com/1991226/28322260-90c875be-6bcd-11e7-8f81-224213b4997e.png)

**Comment by csswizardry** [comment]
Pinged @Heydon about this and #106 👍

**Comment by chriscoffee** [comment]
Can we get in the habit of writing informative bug reports. 

I'm going to guess you did the following to get to this point:
1. You opened (a version of) the index.html sample page in desktop viewport.
2. You then resized the window to a mobile viewport by dragging the window.
3. You then tried to click the burger menu.

You expected the burger menu to automatically open as you clicked it after rezising the window. What actually happened was that it only opened on second/third click after it had been reset.

---

I'm not really going to comment on the implementation of this feature. Yet the common hardline on these are that you could argue that no regular user would ever do this as they're more likely to minimize the page rather than making the page into a mobile viewport, only a developer would do this. However the problem could potentially arise when swapping orientations.

As a side note, it looks like you're using an older release of the framework. Would you be able to either specify this or pull down the latest release and make sure to include which version is broken in the bug report?

**Comment by Heydon** [comment]
@chriscoffee @csswizardry 
Good point about reorientation. I shall take a look. Harry, do you want to ping me when you've integrated with the new version of the framework?

**Comment by Heydon** [comment]
@chriscoffee @csswizardry 

Okay, I completely rewrote the script (https://github.com/csswizardry/nightingale/commit/6775ddad29f19c55d0b73e0e5f1d18011850a414). It now has

* Resize and reorientation support, including rearrangement of submenus in DOM
* Dynamic placement of refs using menu item indexes, so templates don't need to be amended

**Comment by ishanivardhan** [comment]
Any update on whether this is complete, tested? @csswizardry

**Comment by csswizardry** [comment]
@ishanivardhan: Unfortunately, the branch that @Heydon was working in didn’t have any upstream changes merged into it. This means that I can’t `cherry-pick` his commit into our codebase without some pretty heavy-duty merge conflicts. I need to set some time aside to sort it out.

**Comment by Android63** [comment]
Maybe this is Git heresy, but, since this isn't in the main Nightingale repo anyway, couldn't we just add the new js file?

**Comment by csswizardry** [comment]
@Android63: It’s in a fork of the repo, which is (for all intents and purposes) just like being in the repo. In a bind, we could have just done a copy/paste jobbie, but @chriscoffee has got our back! :D

**Comment by cehwitham** [comment]
@Android63 @csswizardry is this resolved now that @chriscoffee has merged in the changes from the other repo?

**Comment by Android63** [comment]
Yes
