### ISSUE TITLE
Logo questions

### ISSUE THREAD

**Issue by Android63** [NHSLeadership/nightingale#113]
I've been looking at the logo. It currently has "NHS" as one image and "Leadership Academy" as another. Does this really make sense?

@Pro-Paul says it should be a single image, but that's not without problems. What if this framework is used by another organisation outside the LA?

And why is the "Leadership Academy" part an image at all? Why not use text? Then, it's more accessible and easier for website admins to change. In my WordPress theme, for example, I'm using the website title here, so it's easy for users to update. The only problem is the font size is smaller than in the image (it uses c-page-header__title).

Finally, should the "NHS" image be hard-coded into the framework or should we allow it to be changed without amending any code? I guess that depends on whether this framework is likely to be used by other organisations outside the NHS.

**Comment by cehwitham** [comment]
@csswizardry any comments on why this implementation was chosen?

**Comment by penpadstudio** [comment]
Logo should be one image i.e. lozenge and text should be one image as the logo format can change dependant on organisation. plus for branding consistency so the spacing is always correct between the lozenge and appropriate text.

**Comment by csswizardry** [comment]
> What if this framework is used by another organisation outside the LA? […] Finally, should the "NHS" image be hard-coded into the framework or should we allow it to be changed without amending any code?

The image only exists in the HTML, which is not part of the framework (which is CSS/Sass only).

> And why is the "Leadership Academy" part an image at all?

Because, despite looking like only text, it is technically a logo. If we had it in text:

* it could render incorrectly (think Windows…);
* it could use an entirely different font;
* the text would get translated by Google Translate et al;
* Google Image searches would not yield the correct logo (this is the weakest point of the lot).

I’m happy for it to just be one image. Will solve as part of #121.
