### ISSUE TITLE
Ribbons

### ISSUE THREAD

**Issue by penpadstudio** [NHSLeadership/nightingale#170]
Ribbons seem to have a hight more than 40px that is taking up valuable page space (noticed whilst working on Moodle theme):
<img width="1027" alt="screen shot 2017-09-21 at 16 39 09" src="https://user-images.githubusercontent.com/23170050/30704714-6b30438a-9eeb-11e7-8513-95547c55568e.png">

**Comment by csswizardry** [comment]
It’s vital to remember that the web doesn’t really work in heights; font rendering, pixel-rounding, and (allowing the) natural flow of content means that heights are much harder to stick to than widths. It’s important that we don’t try to aim for specific pixel values.

Is the issue here that the padding is too great, or…?

Small things like this, it would be beneficial if others could dive in and make changes too :)

Cheers!

**Comment by cehwitham** [comment]
No need for you to fix this @csswizardry.

We've looked into it in the office and a more specific report is:

Padding top and botton on the .c-ribbon class is currently set to 15px. This should be 10px reducing the overall banner height to 46px rather than the current 56px.

Someone in our team will pick this up and push a fix.
