### ISSUE TITLE
Middleware Discussion

### ISSUE THREAD

**Issue by Android63** [NHSLeadership/nightingale#39]
I'm working on integrating Nightingale into our Wordpress theme (which is based on the Underscores theme) and I'm not sure how to handle the styling of widgets since their markup is outside my control.

I registered three widget areas in the footer by adding three versions of the following code to the `nightingale_wp_widgets_init` function (in `functions.php`):

```PHP
register_sidebar( array(
	'name' => __( 'Footer Widget Area 1', 'nightingale-wp' ),
	'id' => 'footer-widget-area-1',
	'description' => __( 'The first footer widget area', 'nightingale-wp' ),
	'before_widget' => '<div class="o-layout__item  u-4/12@lg">',
	'after_widget' => '</div>',
	'before_title' => '<h4 class="widget-title">',
	'after_title' => '</h4>',
) );
```
I then added the following code to `footer.php` to output the contents of all three widgets:

```PHP
<aside class="o-wrapper" role="complementary">
	<div class="o-layout">
               <?php dynamic_sidebar( 'footer-widget-area-1' ); ?>
               <?php dynamic_sidebar( 'footer-widget-area-2' ); ?>
               <?php dynamic_sidebar( 'footer-widget-area-3' ); ?>
	</div>
</aside>
```
This works fine and I can drop three widgets into these areas and they display correctly in three columns. However, unordered lists, for example, are displayed with bullet points. Of course, I could apply a custom css rule to overcome this, but I expect there's a more elegant solution - one that allows us to make use of the existing styling in the Nightingale framework.

**Comment by csswizardry** [comment]
UPDATE: Changed scope from **Styling for Wordpress widgets**

**Comment by cehwitham** [comment]
So few options to explore from the WordPress side before we get too involved on the Sass side.

On our current website we use "Spots" which is a plugin that allows you to create content in a similar way to posts or pages but you can assign a specific template to them and then output them in widget areas or in content bodies of other content. So you could create a "panel" template and a "progress tracker" template that you can use with spots then include these in other content. So the template takes care of all the custom HTML markup and the editor gives you an easy UI to input the data without getting technical.

[WordPress Spots Plugin](https://en-gb.wordpress.org/plugins/spots/)

There is a new editor proposed for WP Core 5.0 to be released before the year is out. Gutenberg provides a new way to edit blocks of content in a user-friendly way. I'm unsure of the templating options and how customisable it is. Functionality is available as a beta plugin currently. It's probably worth us investigating whether this is a good option? I believe it will also be used in widget editing so could be interesting.

[WP Tavern article on Gutenberg](https://wptavern.com/wordpress-new-gutenberg-editor-now-available-as-a-plugin-for-testing)

[WordPress Gutenberg Plugin](https://wordpress.org/plugins/gutenberg/)

A third option would be something like Advanced Custom Fields (ACF) but an external company used this on V1 of the Corporate Website and we had all kinds of compatibility issues and licensing costs. It's improved considerably since but still leads to plugin lock in and not sure I'm a fan. It is used by other people including GDS I believe so maybe worth considering.

[Advanced Custom Fields](https://www.advancedcustomfields.com/)

There is an open source alternative to ACF that we currently use, Custom Metaboxes. This provides most of the functionality of ACF but you setup the custom fields through a JSON file rather than the UI so we keep control rather than users being able to add all kinds of crazy!

[Humanmade Custom Metaboxes](https://github.com/humanmade/Custom-Meta-Boxes)

@Android63 could you have a look at Gutenberg and compare it to our current setup and then we'll have a discussion?

**Comment by Android63** [comment]
Update: For ul elements in footer widgets, I'm using @extend to map Nightingale styling to WordPress as proposed in option 3 by @csswizardry. This is a simple and easy way to apply Nightingale styling without changing any markup and it will work no matter what the user places in the footer widget areas. I envision using the same technique for Gravity Forms. I'll read up on the Gutenberg and let's discuss further @cehwitham

**Comment by csswizardry** [comment]
Just a polite reminder: `@extend` is a bit of an anti-pattern[1] and should only be used where no other option is available 👍 

1. [csswizardry.com/code-smells-in-css-revisited/#extend](https://csswizardry.com/2017/02/code-smells-in-css-revisited/#extend)
