### ISSUE TITLE
Search bar for header

### ISSUE THREAD

**Issue by cehwitham** [NHSLeadership/nightingale#86]
![screen shot 2017-07-12 at 17 18 27](https://user-images.githubusercontent.com/2518941/28128012-2dac096a-6726-11e7-880f-39fa95eea1db.png)

**Comment by penpadstudio** [comment]
We also need a search bar as its own element for Moodle.

**Comment by Android63** [comment]
@csswizardry please review this code to make sure it's BEM and ITCSS compatible.

**Comment by Android63** [comment]
In particular @csswizardry, I created a class called `c-search__input` which is an extension of `c-form-input` (using @extend), but that parent-child relationship isn't reflected in its name. Perhaps it should be named something like `c-form__input-c-search-input`, but that seems very clumsy and long-winded.

Also, in order to position the button (with magnifier icon) inside the input box, I set its margin to -42px. It works for now but maybe there's a better way.
