### ISSUE TITLE
Card container, collapsed and with information

### ISSUE THREAD

**Issue by cehwitham** [NHSLeadership/nightingale#93]
![screen shot 2017-07-12 at 17 14 17](https://user-images.githubusercontent.com/2518941/28127754-8e992d8a-6725-11e7-9f3b-d5e2970c8ae1.png)

**Comment by csswizardry** [comment]
I think this can be marked as done as [the mechanism exists to show and hide content inside of these Media cards](https://github.com/NHSLeadership/nightingale/blob/d817da58683ff9e9723a76d2aee799d5bf3b1848/index.html#L316-L352). The `__reveal` sub-component can house any content we like (currently it’s a transcript, but it can easily be a progress bar, buttons, etc.), so I feel like this issue is solved in more general terms.

Please reopen if you feel I’ve missed anything! cc. @Pro-Paul @cehwitham
